apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dump-workspace
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
      type: string
      description: image containing find commando
      default: registry.redhat.io/ubi8/openjdk-21:latest
  results:
    - name: output
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - |
          set -ex
          find /workspace
      image: $(params.IMAGE)
      name: 'dump-workspace'

      
