---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: maven-pipeline-run-
  finalizers:
    - chains.tekton.dev/pipelinerun
  labels:
    tekton.dev/pipeline: maven-pipeline
spec:
  params:
    - name: GIT_URL
      value: 'https://github.com/hdaems/sandbox2529repo.git'
    - name: MVN_GOALS
      value: ["-DskipTests", "clean", "package"]
    - name: MVN_CONTEXT_DIR
      value: 'code-with-quarkus'
  pipelineRef:
    name: maven-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi

