---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
data: 
  settings.xml: |-
    <settings>
      <mirrors>
        <mirror>
          <id>maven-public</id>
          <url>http://nexus.nexus.svc.cluster.local:8081/content/groups/public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
      <servers>
        <server>
          <id>nexus</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
      </servers>
      <localRepository>/workspace/maven-m2/.m2/repository</localRepository>
    </settings>
